name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
            uses: actions/setup-node@v3
            with:
              node-version: '16'

      - name: Install and Build
        run: |
          npm i pnpm -g
          pnpm install
          pnpm run build  --base=/learn_atctions/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
